run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
  disable:
    - depguard

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
        severity: error
      - name: unexported-return
        severity: error
  gofmt:
    simplify: true
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

severity:
  default-severity: error
