// Package llm provides a multi-provider large language model integration layer
// with chat completion, streaming, embeddings, and prompt templating.
package llm

import (
	"context"
	"errors"
	"time"
)

// ErrNotSupported is returned when a provider does not implement an operation.
var ErrNotSupported = errors.New("operation not supported by this provider")

// Role identifies the sender of a chat message.
type Role string

const (
	// RoleSystem marks a system-level instruction message.
	RoleSystem Role = "system"
	// RoleUser marks a message from the end user.
	RoleUser Role = "user"
	// RoleAssistant marks a message generated by the model.
	RoleAssistant Role = "assistant"
)

// Message represents a single message in a chat conversation.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
}

// Request holds the parameters for a chat completion call.
type Request struct {
	Model       string            `json:"model"`
	Messages    []Message         `json:"messages"`
	MaxTokens   int               `json:"max_tokens,omitempty"`
	Temperature float64           `json:"temperature,omitempty"`
	TopP        float64           `json:"top_p,omitempty"`
	Stream      bool              `json:"stream,omitempty"`
	Stop        []string          `json:"stop,omitempty"`
	UserID      string            `json:"-"`
	Metadata    map[string]string `json:"-"`
}

// Response holds the result of a chat completion call.
type Response struct {
	ID           string        `json:"id"`
	Model        string        `json:"model"`
	Content      string        `json:"content"`
	FinishReason string        `json:"finish_reason"`
	Usage        TokenUsage    `json:"usage"`
	Latency      time.Duration `json:"latency"`
}

// TokenUsage reports token consumption for a single request.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// StreamChunk represents a single piece of a streaming response.
type StreamChunk struct {
	Content      string
	FinishReason string
	Err          error
}

// EmbeddingRequest holds parameters for an embedding call.
type EmbeddingRequest struct {
	Model  string   `json:"model"`
	Texts  []string `json:"input"`
	UserID string   `json:"-"`
}

// EmbeddingResponse holds vector embeddings for input texts.
type EmbeddingResponse struct {
	Model      string      `json:"model"`
	Embeddings [][]float64 `json:"embeddings"`
	Usage      TokenUsage  `json:"usage"`
}

// ModelInfo describes a model available from a provider.
type ModelInfo struct {
	ID                string  `json:"id"`
	Provider          string  `json:"provider"`
	MaxTokens         int     `json:"max_tokens"`
	InputPrice        float64 `json:"input_price"`
	OutputPrice       float64 `json:"output_price"`
	SupportsVision    bool    `json:"supports_vision"`
	SupportsStreaming bool    `json:"supports_streaming"`
	SupportsEmbedding bool    `json:"supports_embedding"`
}

// Config holds common configuration for all providers.
type Config struct {
	APIKey      string
	SecretID    string // Tencent Cloud API SecretId (TC3 signing)
	SecretKey   string // Tencent Cloud API SecretKey (TC3 signing)
	Region      string // Tencent Cloud region for TC3
	Endpoint    string
	Model       string
	MaxTokens   int
	Temperature float64
	TopP        float64
	Timeout     time.Duration
	OrgID       string
	Headers     map[string]string
}

// Provider defines the interface that all LLM adapters must satisfy.
type Provider interface {
	// Name returns the provider identifier (e.g. "openai", "claude").
	Name() string
	// Chat performs a synchronous chat completion.
	Chat(ctx context.Context, req Request) (*Response, error)
	// ChatStream performs a streaming chat completion, returning chunks
	// on the returned channel until the response is complete.
	ChatStream(ctx context.Context, req Request) (<-chan StreamChunk, error)
	// Embed generates vector embeddings for the given texts.
	Embed(ctx context.Context, req EmbeddingRequest) (*EmbeddingResponse, error)
	// ListModels returns the models available from this provider.
	ListModels(ctx context.Context) ([]ModelInfo, error)
	// Available reports whether the provider is currently reachable.
	Available(ctx context.Context) bool
}
